const $=id=>document.getElementById(id),s1=$('s1'),s2=$('s2'),s3=$('s3'),s4=$('s4'),yes=$('yes'),no=$('no'),tease=$('tease'),date=$('date'),next=$('next'),lock=$('lock'),summary=$('summary'),message=$('message'),badge=$('badge'),modal=$('modal'),close=$('close'),fallLayer=$('fallLayer'),dateLabel=document.querySelector('.datebox label'),opts=[...document.querySelectorAll('.option')],sunFace=$('sunFace'),ticketDate=$('ticketDate'),ticketVibe=$('ticketVibe'),ticketCountdown=$('ticketCountdown'),barcode=$('barcode');
let n=0,chosen='';
const STORAGE_KEY='marinaDatePlanV1';
const EMAIL_ENDPOINT='https://formsubmit.co/ajax/Andrew.hana2000@gmail.com';
const msgs=['Interesting choice. The YES button has filed an appeal.','Are you suuuure? It appears to be getting stronger.','Marina. The pink city is literally watching.','Okay, now the flowers are judging you.','Girl be serious.'];
function show(a,b){a.classList.remove('show');b.classList.add('show')}
function showOnly(step){[s1,s2,s3,s4].forEach(x=>x.classList.remove('show'));step.classList.add('show')}
function pop(x=innerWidth/2,y=innerHeight/2,count=25){for(let i=0;i<count;i++){let e=document.createElement('span');e.className='burst';e.textContent=['♡','♥','✿','✨','🌸'][i%5];e.style.left=x+'px';e.style.top=y+'px';e.style.setProperty('--x',(Math.random()*300-150)+'px');e.style.setProperty('--y',(Math.random()*300-160)+'px');e.style.setProperty('--r',(Math.random()*360)+'deg');document.body.appendChild(e);setTimeout(()=>e.remove(),950)}}
function skyBurst(){const pts=[[innerWidth*.2,innerHeight*.16],[innerWidth*.38,innerHeight*.24],[innerWidth*.58,innerHeight*.18],[innerWidth*.76,innerHeight*.22],[innerWidth*.84,innerHeight*.11]];pts.forEach((p,i)=>setTimeout(()=>pop(p[0],p[1],18),i*120));}
function flashWindows(){document.body.classList.remove('window-flash');void document.body.offsetWidth;document.body.classList.add('window-flash');setTimeout(()=>document.body.classList.remove('window-flash'),1400)}
function updateNoMood(){tease.textContent=msgs[Math.min(n-1,msgs.length-1)];no.textContent=n<3?'No':n<5?'Still no':'...no?';document.body.classList.toggle('sad-flowers',n>=3);document.body.classList.toggle('serious',n>=5);if(sunFace)sunFace.textContent=n>=5?'☹':'♡';if(sunFace&&n>=5)sunFace.style.color='#f5e7f0';flashWindows();}
function prettyDate(value){return new Date(value+'T12:00:00').toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'})}
function countdownFor(value){const d=new Date(value+'T12:00:00'),today=new Date(),start=new Date(today.getFullYear(),today.getMonth(),today.getDate()),target=new Date(d.getFullYear(),d.getMonth(),d.getDate()),days=Math.max(0,Math.round((target-start)/86400000));return days===0?'Today ♡':days===1?'1 day to go ♡':`${days} days to go ♡`}
function savePlan(plan){localStorage.setItem(STORAGE_KEY,JSON.stringify(plan))}
function loadPlan(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'null')}catch(_){return null}}
function renderLockedPlan(plan,{animate=false}={}){if(!plan||!plan.date||!plan.vibe)return;const pretty=prettyDate(plan.date);summary.innerHTML=`<strong>${pretty}</strong><br>${plan.vibe}<br><br>Official status: extremely cute and 100% happening. ♡`;ticketDate.textContent=pretty;ticketVibe.textContent=plan.vibe;ticketCountdown.textContent=countdownFor(plan.date);barcode.textContent=`M+A • ${plan.date.replaceAll('-','')} • ♡`;document.body.classList.add('night');showOnly(s4);message.classList.add('show');if(plan.messageRead){badge.classList.add('read');message.classList.remove('unread');message.setAttribute('aria-label','New message')}else{badge.classList.remove('read');message.classList.add('unread');message.setAttribute('aria-label','1 new message')}if(animate){pop(innerWidth/2,innerHeight/2,34);skyBurst();document.body.classList.add('celebrate');setTimeout(()=>document.body.classList.remove('celebrate'),1800)}}
async function maybeSendEmail(plan){if(!EMAIL_ENDPOINT||plan.emailSent)return;try{const data=new FormData();data.append('status','Marina locked in the date.');data.append('date',prettyDate(plan.date));data.append('date_value',plan.date);data.append('date_vibe',plan.vibe);data.append('message',`Marina picked ${prettyDate(plan.date)} with the vibe: ${plan.vibe}.`);data.append('locked_at',plan.lockedAt);data.append('source',location.href);data.append('_subject','Marina locked in a date ♡');data.append('_template','table');data.append('_captcha','false');const res=await fetch(EMAIL_ENDPOINT,{method:'POST',headers:{'Accept':'application/json'},body:data});if(!res.ok)throw new Error('send failed');plan.emailSent=true;plan.emailSentAt=new Date().toISOString();savePlan(plan)}catch(_){/* leave unsent so a later refresh can retry */}}
no.onclick=()=>{n++;yes.style.setProperty('--s',Math.min(1+n*.28,3.1));updateNoMood()};
yes.onclick=e=>{pop(e.clientX||innerWidth/2,e.clientY||innerHeight/2,28);setTimeout(()=>show(s1,s2),250)};
let t=new Date;t.setDate(t.getDate()+1);date.min=[t.getFullYear(),String(t.getMonth()+1).padStart(2,'0'),String(t.getDate()).padStart(2,'0')].join('-');date.onchange=()=>next.disabled=!date.value;
function openDatePicker(){try{if(typeof date.showPicker==='function')date.showPicker();else date.focus()}catch(_){date.focus()}}
date.addEventListener('click',openDatePicker);date.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openDatePicker()}});if(dateLabel)dateLabel.addEventListener('click',e=>{e.preventDefault();date.focus();openDatePicker()});
next.onclick=()=>date.value&&show(s2,s3);
opts.forEach(o=>o.onclick=()=>{opts.forEach(x=>x.classList.remove('selected'));o.classList.add('selected');chosen=o.dataset.v;lock.disabled=false});
lock.onclick=e=>{if(!date.value||!chosen)return;const existing=loadPlan();if(existing?.date&&existing?.vibe){renderLockedPlan(existing);return}const plan={date:date.value,vibe:chosen,lockedAt:new Date().toISOString(),messageRead:false,emailSent:false};savePlan(plan);renderLockedPlan(plan,{animate:true});maybeSendEmail(plan)};
message.onclick=()=>{badge.classList.add('read');message.classList.remove('unread');message.setAttribute('aria-label','New message');const plan=loadPlan();if(plan){plan.messageRead=true;savePlan(plan)}modal.classList.add('show');close.focus()};
function shut(){modal.classList.remove('show');message.focus()} close.onclick=shut;modal.onclick=e=>{if(e.target===modal)shut()};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal.classList.contains('show'))shut()});
(function makeFalling(){if(!fallLayer||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const symbols=['✿','♡','🌸','✦','♡','✿'];for(let i=0;i<34;i++){const el=document.createElement('span');el.className='falling';el.textContent=symbols[i%symbols.length];el.style.left=(Math.random()*100)+'%';el.style.fontSize=(12+Math.random()*17)+'px';el.style.color=i%5===0?'#ffe998':i%3===0?'#ffffff':'#fff0f7';el.style.setProperty('--dur',(8+Math.random()*9)+'s');el.style.setProperty('--delay',(-Math.random()*16)+'s');el.style.setProperty('--drift',(Math.random()*110-55)+'px');fallLayer.appendChild(el)}})();
const savedPlan=loadPlan();if(savedPlan?.date&&savedPlan?.vibe){renderLockedPlan(savedPlan);maybeSendEmail(savedPlan)}
